### ISSUE TITLE
finding the best off the shelf component for RTE Editor

### ISSUE THREAD

**Issue by adriatic** [adriatic/aureliatools-design-discussions#8]

**Comment by JeroenVinke** [comment]
https://ace.c9.io/#nav=about

**Comment by adriatic** [comment]
A 100% agreement achieved independently - as I have it running since yesterday

![image](https://cloud.githubusercontent.com/assets/2712405/12821546/d5764bf2-cb31-11e5-8ad8-f54a513380a3.png)

This is a good time to share more context: The above screenshot was created when  running the "old javascript based project" shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/12821669/51b57c56-cb32-11e5-8a89-c43d284ca836.png)

with **[this](https://ace.c9.io/#nav=embedding)** index.html file

So, later in the evening yesterday, I decide to surprise you when you wake up this morning and see the RTE code editor created by using the Bridge Skeleton as the starter project, implement the ACE as a custom element and have the very first RTE  code editor as a "legal" Aurelia app.

Then my jinx kicked in again - resulting with Bridge Skeleton acting up in completely unexpected way, precisely in the area I wanted to use as the model for ACE as custom element (the au-markdown).

#### By the way, I still did not find the explanation about why is Bridge Skeleton failing
I saw an email with the reference to Github, where you have a reference to some code, but did not yet "process" this information.

**Comment by JeroenVinke** [comment]
Very nice ;)

**Comment by adriatic** [comment]
We could likely close this item as it is hard to believe that we will find something better :-)
